
include: package:flutter_lints/flutter.yaml
analyzer:
  # strong-mode:
  #   implicit-casts: true
  errors:
    undefined_prefixed_name: ignore
    invalid_annotation_target: ignore


  exclude: [lib/**.g.dart]

linter:
  rules:
    avoid_print: true # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    prefer_relative_imports: true
    flutter_style_todos: false
    prefer_foreach: true
    file_names: true
    unnecessary_this: true
    require_trailing_commas: true
    unnecessary_const: true

