name: music_player
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  dio: ^5.4.2+1
  just_audio: ^0.9.37
  audio_video_progress_bar: ^2.0.2
  flutter_hooks: ^0.20.5
  app_settings: ^5.1.1
  sprintf: ^7.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.0
  flutter_sound: ^9.4.6
  path_provider: ^2.1.2
  firebase_core: ^2.15.1
  cloud_firestore: ^4.13.6
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: 
  auto_route_generator: ^7.3.1


# flutter clean && flutter pub get && flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path:  "assets/images/icon_luancher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/svgs/
    - assets/animation/

